<?php include(__DIR__.'/../../../layout/header.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h4>编辑页面</h4>
            <hr>
            <form class="form-horizontal">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="username">帐号：</label>
                        </div>
                        <div class="col-md-9">
                            <input class="form-control" type="text" id="username" placeholder="输入帐号" value="">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="password">密码：</label>
                        </div>
                        <div class="col-md-9">
                            <input class="form-control" type="text" id="password" placeholder="输入密码" value="">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="mail">邮箱：</label>
                        </div>
                        <div class="col-md-9">
                            <input class="form-control" type="text" id="mail" placeholder="输入邮箱" value="">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="tel">电话：</label>
                        </div>
                        <div class="col-md-9">
                            <input class="form-control" type="text" id="tel" placeholder="输入密码" value="">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-1">
                            <button type="button" id="save" class="btn btn-default">保存</button>
                        </div>
                        <div class="col-md-3">
                            <button type="button" id="reset" class="btn btn-default">重填</button>
                        </div>
                        <div class="col-md-3">
                            <button type="button" id="cancel" class="btn btn-default">取消</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="userid" value="">
            </form>
            <!--end form-->
        </div>
        <!--end col-->
    </div>
    <!--end row-->
</div>
<!--end container-->
<?php include(__DIR__.'/../../../layout/footer.phtml'); ?>
<script src="/js/user-edit.js"></script>
