<?php include(__DIR__.'/../../../layout/header.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading text-center">Bunny User Example</div>
                <table class="table table-striped table-bordered table-hover table-condensed">
                    <tr id="table-th">
                        <th class="text-center">帐号</th>
                        <th class="text-center">密码</th>
                        <th class="text-center">邮箱</th>
                        <th class="text-center">电话</th>
                        <th class="text-center">操作</th>
                    </tr>
                </table>
            </div>
            <div class="panel-heading text-center">
                <nav id="page">
                </nav>
            </div>
        </div>
        <!--end panel-->
    </div>
    <!--end col-->
</div>
<!--end row-->
</div>
<!--end container-->
<!--html body部分 结束-->
<?php include(__DIR__.'/../../../layout/footer.phtml'); ?>
<script src="/js/user-index.js"></script>
